export {default as Navbar} from './navbar/Navbar';
export {default as Header} from './header/Header';
export {default as Abouts} from './about/RenderAbout'
export {default as Social} from './social/Social'
export {default as Stack} from './stack/Stack'
export {default as Faq} from './faq/Faq';
export {default as Footer} from './footer/Footer'
export {default as Project} from './projects/Projects'
export {default as Contact} from './contact/Contact'